### ISSUE TITLE
Linux compatibility

### ISSUE THREAD

**Issue by christian179717** [Sammy-T/avda#28]
Will there be a Linux app too?

For me, it seems there is no version for Linux, or am I wrong?

**Comment by Sammy-T** [comment]
The [release page](https://github.com/Sammy-T/avda/releases) includes an executable that can be extracted from `avda_linux.zip`. Do you see any errors when you run the executable from the terminal?

**Comment by christian179717** [comment]
Thanks, works

**Comment by RobinFrcd** [comment]
@christian179717 Does it work well on your Linux install ?
Mine is completely buggy (on Ubuntu `22.04`). I've tried running it in Firefox, and it works fine, so I guess the issue comes from wails. :/

**Comment by christian179717** [comment]
@RobinFrcd I'm using Manjaro with Plasma:

Operating System: Manjaro Linux 
KDE Plasma Version: 6.2.4
KDE Frameworks Version: 6.8.0
Qt Version: 6.8.1
Kernel Version: 6.11.11-1-MANJARO (64-bit)
Graphics Platform: X11

After a while, it's kind of buggy, since the copy buttons move to somewhere they shouldn't be @Sammy-T :

![Image](https://github.com/user-attachments/assets/c885f340-d4c2-482b-9050-c4188a7b5749)

![Image](https://github.com/user-attachments/assets/ff00a1f6-3dfb-4a5f-ab83-69ea1cc6183e)

But this is only after moving the window in the background, so it's not optimal, but I can live with that.

**Comment by Sammy-T** [comment]
@christian179717, are you using the latest release of the app?

@RobinFrcd, are the issues you're seeing the same as christian's?

**Comment by RobinFrcd** [comment]
@Sammy-T Hey, not at all, mine are pretty huge performances issues. I basically have 2 FPS on it, and it uses 100% CPU :/

**Comment by christian179717** [comment]
@Sammy-T was on v1.5.0
Seems to be fixed now.

Do you know if avda is already in some repos like pacman/flatpak/snap so it can be upgraded with the system tools? Or could you integrate a feature which checks if a new version is available?

**Comment by Sammy-T** [comment]
@christian179717 Glad it's working for you now.

I can't make any promises at this time about updating via system tools but adding a "new version available" indicator is on my todo list.

**Comment by RobinFrcd** [comment]
@Sammy-T Updated to 24.04, Gnome 46 Wayland indeed works better now !
